const S={id:crypto.randomUUID(),name:"",pc:null,ch:null,files:new Map(),total:0};
const $=x=>document.getElementById(x),esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(s){let e=$("toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function detect(){let u=navigator.userAgent;S.name=localStorage.swiftName||(u.includes("Android")?"Android device":u.includes("Windows")?"Windows PC":"Browser device");$("device").textContent=S.name;$("info").textContent=u.includes("Android")?"Android • Browser":u.includes("Windows")?"Windows • Browser":"Browser";$("net").textContent="● READY"}
function status(s,on=false){$("status").textContent=s;$("state").textContent=on?"ONLINE":"OFFLINE";$("state").style.color=on?"var(--green)":"var(--muted)"}
function log(name,state,p=0,detail=""){let b=$("log");if(b.querySelector("p"))b.innerHTML="";let d=document.createElement("div");d.className="item";d.innerHTML=`<div><b>${esc(name)}</b> <small>${esc(state)}</small></div><div class="bar"><div class="fill" style="width:${p}%"></div></div><small>${esc(detail)}</small>`;b.prepend(d);return d}
function modal(h){$("content").innerHTML=h;$("modal").classList.add("show")};$("x").onclick=()=> $("modal").classList.remove("show");
function sig(kind,payload){return btoa(unescape(encodeURIComponent(JSON.stringify({kind,payload}))))}
function parse(x){try{return JSON.parse(decodeURIComponent(escape(atob(x.trim()))))}catch(e){throw Error("Invalid pairing data")}}
function pc(){let p=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});p.onconnectionstatechange=()=>{status(p.connectionState,p.connectionState==="connected");if(p.connectionState==="connected"){$("modal").classList.remove("show");toast("⚡ Direct connection ready")}};p.ondatachannel=e=>attach(e.channel);return p}
function attach(c){S.ch=c;c.binaryType="arraybuffer";c.bufferedAmountLowThreshold=1024*1024;c.onopen=()=>status("Direct • ready",true);c.onclose=()=>status("Disconnected");c.onmessage=e=>receive(e.data)}
function ice(){return new Promise(r=>{if(S.pc.iceGatheringState==="complete")return r();let f=()=>{if(S.pc.iceGatheringState==="complete"){S.pc.removeEventListener("icegatheringstatechange",f);r()}};S.pc.addEventListener("icegatheringstatechange",f);setTimeout(r,4000)})}
async function host(){S.pc=pc();S.ch=S.pc.createDataChannel("swift");attach(S.ch);let o=await S.pc.createOffer();await S.pc.setLocalDescription(o);await ice();let out=sig("offer",S.pc.localDescription);$("room").textContent="HOST • waiting";status("Waiting for answer");modal(`<h2>⚡ Host pairing</h2><p>Copy this pairing data to the other device.</p><textarea id="out" readonly>${out}</textarea><button onclick="navigator.clipboard.writeText($('out').value);toast('Copied')">Copy</button><button id="answerBtn">Paste answer</button>`);$("answerBtn").onclick=()=>modal(`<h2>Paste answer</h2><textarea id="in" placeholder="Paste answer…"></textarea><button onclick="answer()">Connect</button>`)}
async function answer(){try{let x=parse($("in").value);if(x.kind!=="answer")throw Error("Expected answer");await S.pc.setRemoteDescription(x.payload);$("modal").classList.remove("show")}catch(e){toast(e.message)}}
async function join(){modal(`<h2>Join SwiftShare</h2><p>Paste the host pairing data.</p><textarea id="in" placeholder="Paste host offer…"></textarea><button onclick="offer()">Continue</button>`)}
async function offer(){try{let x=parse($("in").value);if(x.kind!=="offer")throw Error("Expected host offer");S.pc=pc();await S.pc.setRemoteDescription(x.payload);let a=await S.pc.createAnswer();await S.pc.setLocalDescription(a);await ice();let out=sig("answer",S.pc.localDescription);modal(`<h2>Answer ready</h2><p>Copy this back to the host.</p><textarea id="out" readonly>${out}</textarea><button onclick="navigator.clipboard.writeText($('out').value);toast('Copied answer')">Copy answer</button>`);$("room").textContent="GUEST • waiting";status("Waiting for host")}catch(e){toast(e.message)}}
function files(fs){if(!S.ch||S.ch.readyState!=="open")return toast("Connect a device first");[...fs].reduce((p,f)=>p.then(()=>send(f)),Promise.resolve())}
async function send(f){let d=log("📦 "+f.name,"Sending",0,"Starting"),id=crypto.randomUUID(),start=performance.now(),n=0,c=256*1024;S.ch.send(JSON.stringify({t:"start",id,name:f.name,size:f.size,mime:f.type||"application/octet-stream"}));while(n<f.size){while(S.ch.bufferedAmount>4*1024*1024)await new Promise(r=>setTimeout(r,10));let e=Math.min(n+c,f.size),b=await f.slice(n,e).arrayBuffer();S.ch.send(b);n=e;let sec=(performance.now()-start)/1000,sp=n/Math.max(sec,.01);d.querySelector(".fill").style.width=n/f.size*100+"%";d.querySelector("small").textContent=`${fmt(n)} / ${fmt(f.size)} • ${fmt(sp)}/s`;$("speed").textContent=fmt(sp)+"/s"}S.ch.send(JSON.stringify({t:"end",id}));S.total+=f.size;$("total").textContent=fmt(S.total);toast("Sent "+f.name)}
function receive(x){if(typeof x==="string"){try{let m=JSON.parse(x);if(m.t==="start")S.files.set(m.id,{...m,chunks:[],got:0});else if(m.t==="end")finish(m.id);else if(m.t==="text"||m.t==="link"||m.t==="clip")received(m)}catch(_){}}else for(let [id,f] of S.files){f.chunks.push(x);f.got+=x.byteLength;if(f.got>=f.size)finish(id);break}}
function finish(id){let f=S.files.get(id);if(!f)return;let a=document.createElement("a");a.href=URL.createObjectURL(new Blob(f.chunks,{type:f.mime}));a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);S.total+=f.size;$("total").textContent=fmt(S.total);S.files.delete(id);toast("Received "+f.name)}
function received(m){modal(`<h2>📥 ${m.t==="link"?"Link":m.t==="clip"?"Clipboard":"Text"} received</h2><textarea id="recv" readonly>${esc(m.v)}</textarea><button onclick="navigator.clipboard.writeText($('recv').value);toast('Copied')">Copy</button>`)}
function text(kind){if(!S.ch||S.ch.readyState!=="open")return toast("Connect a device first");modal(`<h2>${kind==="link"?"🔗":"📝"} Send ${kind}</h2><textarea id="out" placeholder="Paste here…"></textarea><button onclick="let v=$('out').value;if(v){S.ch.send(JSON.stringify({t:'${kind}',v}));$('modal').classList.remove('show');toast('Sent instantly')}">Send</button>`)}
async function clip(){try{let v=await navigator.clipboard.readText();if(!v)return toast("Clipboard empty");S.ch?.send(JSON.stringify({t:"clip",v}));toast("Clipboard sent")}catch(e){toast("Clipboard permission denied")}}
async function adb(){try{let r=await fetch("http://127.0.0.1:8765/devices");let j=await r.json();modal(`<h2>🤖 ADB Devices</h2><pre>${esc(JSON.stringify(j,null,2))}</pre>`)}catch(e){modal(`<h2>🤖 ADB Bridge</h2><p>GitHub Pages cannot execute ADB itself. Run the included <b>adb-bridge.ps1</b> on Windows, then try again.</p>`)}} 
function fmt(n){let u=["B","KB","MB","GB","TB"],i=0;while(n>=1024&&i<4){n/=1024;i++}return n.toFixed(i?2:0)+" "+u[i]}
$("host").onclick=host;$("join").onclick=join;$("clear").onclick=()=>{$("log").innerHTML="<p>Activity cleared.</p>"};
$("files").onchange=e=>files(e.target.files);$("folder").onchange=e=>files(e.target.files);
document.querySelectorAll(".methods button").forEach(b=>b.onclick=()=>({files:()=>$("files").click(),folder:()=>$("folder").click(),text:()=>text("text"),link:()=>text("link"),clip,adb}[b.dataset.k]()));
detect();status("Waiting");